package org.cabr4.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;

/**
 * JPA entity representing a Customer in the system.
 * This class is mapped to the "customers" table in the database.
 *
 * Note:
 * - This entity represents the persistence model only.
 * - It should not be exposed directly in the API (use DTOs instead).
 */
@Entity
@Table(name = "customers") //Modify table
@NoArgsConstructor
@Getter
@Setter
@ToString
public class Customer {

  /**
   * Primary key generated by the database.
   * The ID is immutable and must not be modified by the application.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Setter(AccessLevel.NONE)
  private Long id;

  /**
   * Customer first name.
   */
  @NotNull
  @NotBlank (message = "The field name is empty, please enter data")
  private String name;

  /**
   * Customer last name.
   * Mapped explicitly to "last_name" column in the database.
   */
  @Column(name = "last_name")
  @NotNull
  @NotBlank (message = "The field last name is empty, please enter data")
  private String lastName;

  /**
   * Contact phone number.
   */

  @NotNull
  @NotBlank (message = "The field phone is empty, please enter data")
  private String phone;

  /**
   * Age stored as String for flexibility (e.g. "18", "unknown").
   * If numeric operations are required, consider using Integer instead.
   */
  @NotNull
  @NotBlank (message = "The field is age empty, please enter data")
  private String age;

  /**
   * Customer email address.
   * In real systems this should be unique and validated.
   */
  @NotNull
  @NotBlank (message = "The field email is empty, please enter data")
  @Email
  private String email;

  /**
   * Hashed password.
   * Excluded from toString() to avoid leaking sensitive data in logs.
   */
  @ToString.Exclude
  @NotNull
  @NotBlank(message = "The field password is empty, please enter data")
  @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
  private String password;

  /**
   * Convenience constructor for creating new Customer instances.
   * The ID is intentionally omitted because it is generated by the database.
   */
  public Customer(String name, String lastName,
                  String phone, String age,
                  String email, String password) {
    this.name = name;
    this.lastName = lastName;
    this.phone = phone;
    this.age = age;
    this.email = email;
    this.password = password;
  }
}
